<?php

use Illuminate\Database\Seeder;

class AttributesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attributes')->delete();
        
        \DB::table('attributes')->insert(array (
            0 => 
            array (
                'id' => 372,
                'name' => 'car_make',
                'display_name' => 'Make',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of all the cars available in Australia.</p>',
                'attribute_value' => 'Alfa Romeo, Aston Martin, Audi, Bentley, BMW, Cherry, Chevrolet, Chrysler, Citroen, Daewoo, Daihatsu, Daimler, Datsun, Detomaso, Fiat, Ford, Holden, Honda, Hyundai, Infiniti, Jaguar, Jeep, KIA,  Lexus, Mazda, Mercedes, Mitsubishi, Morris, Nissan, Opel, Peugeot, Porsche,  Proton, Renault, Rolls Royce, Rover, Saab, Skoda, Smart, Subaru, Suzuki, Toyota, Vauxhall, Volkswagen, Volvo',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 14:04:16',
                'updated_at' => '2017-04-28 23:45:52',
            ),
            1 => 
            array (
                'id' => 374,
                'name' => 'make_year',
                'display_name' => 'Year',
                'p_attr_id' => 0,
                'attributetype_id' => 8,
                'description' => '<p>List of car manufactured year.</p>',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '65506.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 15:36:13',
                'updated_at' => '2017-05-26 14:11:08',
            ),
            2 => 
            array (
                'id' => 375,
                'name' => 'vehcile_km',
                'display_name' => 'Kilometers',
                'p_attr_id' => 0,
                'attributetype_id' => 1,
                'description' => '<p>List all the KM done by the car</p>
',
                'attribute_value' => '',
                'size' => 10,
                'measure_unit' => 'KM',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '77259.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 15:40:34',
                'updated_at' => '2017-05-26 14:15:29',
            ),
            3 => 
            array (
                'id' => 377,
                'name' => 'vehc_transmission',
                'display_name' => 'Transmission',
                'p_attr_id' => 0,
                'attributetype_id' => 7,
                'description' => '<p>Select the transmission type of the car.</p>',
                'attribute_value' => 'Automatic,Manual',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '86621.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 15:46:15',
                'updated_at' => '2017-05-26 14:10:02',
            ),
            4 => 
            array (
                'id' => 378,
                'name' => 'vehc_fueltype',
                'display_name' => 'Fuel Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>Vehcile engine fuel type</p>
',
                'attribute_value' => 'Petrol, Diesel, Hybrid, LPG,Electric',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '23774.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 15:49:55',
                'updated_at' => '2017-05-26 14:16:03',
            ),
            5 => 
            array (
                'id' => 379,
                'name' => 'vehcile_airconditioned',
                'display_name' => 'Airconditioned',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>Shows that Vehcile is airconditioned or not</p>',
                'attribute_value' => 'Yes, No',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 15:52:33',
                'updated_at' => '2017-04-28 15:52:33',
            ),
            6 => 
            array (
                'id' => 380,
                'name' => 'vehcile_registration',
                'display_name' => 'Registered',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>Shows that Vehcile is registered or not</p>',
                'attribute_value' => 'Yes,No',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 15:54:53',
                'updated_at' => '2017-04-28 15:54:53',
            ),
            7 => 
            array (
                'id' => 381,
                'name' => 'vehcile_color',
                'display_name' => 'Color',
                'p_attr_id' => 0,
                'attributetype_id' => 12,
                'description' => '<p>Show the color of the Vehcile</p>',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 15:56:10',
                'updated_at' => '2017-11-08 11:13:22',
            ),
            8 => 
            array (
                'id' => 382,
                'name' => 'type_of_post',
                'display_name' => 'Type of Post',
                'p_attr_id' => 0,
                'attributetype_id' => 7,
                'description' => '<p>Show that what kind of job post is it</p>
',
                'attribute_value' => ' Looking for Job,Looking for Resource',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 16:14:20',
                'updated_at' => '2017-04-29 01:37:50',
            ),
            9 => 
            array (
                'id' => 383,
                'name' => 'job_type',
                'display_name' => 'Job Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>The type of contract a user </p>',
                'attribute_value' => 'Permanent, Temp, Contract',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 16:18:58',
                'updated_at' => '2017-11-17 06:10:17',
            ),
            10 => 
            array (
                'id' => 384,
                'name' => 'salary_type',
                'display_name' => 'Salary Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>The salary type which a user is looking for or will get from employer</p>',
                'attribute_value' => 'Hourly, Weekly, Monthly,Yearly',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 16:21:04',
                'updated_at' => '2017-11-16 10:51:24',
            ),
            11 => 
            array (
                'id' => 385,
                'name' => 'salary_range',
                'display_name' => 'Salary Range',
                'p_attr_id' => 0,
                'attributetype_id' => 18,
                'description' => '<p>Salary range will help employer in setting range of the salary which a user will get</p>',
                'attribute_value' => '1000,10000',
                'size' => 10,
                'measure_unit' => 'AUD',
                'required' => 0,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 16:23:34',
                'updated_at' => '2017-11-16 10:51:43',
            ),
            12 => 
            array (
                'id' => 386,
                'name' => 'job_experinece',
                'display_name' => 'Experience',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>The required field for the number of experience a user must have.</p>',
                'attribute_value' => '0,1,2,3,4,5,6,7,8,9,10, More than 10 years',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 16:28:11',
                'updated_at' => '2017-04-28 16:28:11',
            ),
            13 => 
            array (
                'id' => 387,
                'name' => 'accounting_func_area',
                'display_name' => 'Functional Area',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>Functional area of Accounting&nbsp;</p>',
                'attribute_value' => 'Bookkeeping,Accounting,Accounts Officer,
Accounts Payable,
Financial Accounting & Reporting,
Payroll Accounting,
Taxation,
Accounts Receivable,
Credit Control,
Business Services &amp; Corporate,
Advisory,
Financial Manager &amp; Controller,
Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 16:32:19',
                'updated_at' => '2017-04-28 23:54:10',
            ),
            14 => 
            array (
                'id' => 388,
                'name' => 'administrative_func_area',
                'display_name' => 'Functional Area',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the functional areas of the Job</p>',
                'attribute_value' => 'Administrative Assistant,Client &amp; Sales Administration,Contracts Administration,Data Entry &amp, Word Processing,Office Management,PA, EA &amp; Secretarial,Receptionists,Records Management,Document Control,Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 16:56:25',
                'updated_at' => '2017-04-28 23:54:30',
            ),
            15 => 
            array (
                'id' => 389,
                'name' => 'advertisment_func_area',
                'display_name' => 'Functional Area',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the functioanl area of the job advertisment</p>',
                'attribute_value' => 'Performing Arts,Writing,  Journalist,Media Planning, Strategy &amp; Buying, Account Manager,Art Director,Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 16:58:42',
                'updated_at' => '2017-04-28 16:58:42',
            ),
            16 => 
            array (
                'id' => 390,
                'name' => 'banking_func_area',
                'display_name' => 'Banking & Financial Services',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the banking and financial services</p>',
                'attribute_value' => 'Financial Planning, Mortgage Broker, Funds Management, Account, Relationship Management, Analysis, Reporting,Banking - Retail/Branch, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:01:33',
                'updated_at' => '2017-04-28 17:01:33',
            ),
            17 => 
            array (
                'id' => 391,
                'name' => 'customer_func_area',
                'display_name' => 'Functional Area',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the functioanl area in call center jobs</p>',
                'attribute_value' => 'Sales - Call Centre,Customer Service - Call Centre,Customer Service, Customer Facing,Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:09:37',
                'updated_at' => '2017-04-28 17:09:37',
            ),
            18 => 
            array (
                'id' => 398,
                'name' => 'Community Services _func_area',
                'display_name' => 'Community Services & Development ',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Cars, Vans &amp; Utes&nbsp;Functional Area.</p>',
                'attribute_value' => 'Aged & Disability Support, Child Welfare, Youth&Family Services , Employment Services, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:30:40',
                'updated_at' => '2017-04-28 23:55:49',
            ),
            19 => 
            array (
                'id' => 399,
                'name' => 'Construction_func_area',
                'display_name' => 'Construction',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Community Services &amp; Development Functional Area.</p>',
                'attribute_value' => 'Machine & Plant Operator, Foreman/Supervisor, Contract Management, Project Management, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:32:27',
                'updated_at' => '2017-04-28 17:32:27',
            ),
            20 => 
            array (
                'id' => 400,
                'name' => 'Design_func_area',
                'display_name' => 'Design & Architecture ',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Construction Functional Area.</p>',
                'attribute_value' => 'Architecture, Graphic Design, Interior Design, Interaction, Web Design,Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:34:20',
                'updated_at' => '2017-04-28 23:57:10',
            ),
            21 => 
            array (
                'id' => 401,
                'name' => 'Education_func_area',
                'display_name' => 'Education & Teaching ',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Construction Functional Area.</p>',
                'attribute_value' => 'Tutoring, Management, Childcare, After School Care,Teaching, Workplace, Training, Assessment, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:36:44',
                'updated_at' => '2017-04-28 23:57:31',
            ),
            22 => 
            array (
                'id' => 402,
                'name' => 'Engineering_func_area',
                'display_name' => 'Engineering ',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Education &amp; Teaching Functional Area.</p>',
                'attribute_value' => 'Civil/Structural Engineering, Aerospace Engineering, Water and waste Engineering, Mechanical Engineering, Building, Services Engineering, Automotive Engineering, Maintenance, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:38:44',
                'updated_at' => '2017-04-28 17:38:44',
            ),
            23 => 
            array (
                'id' => 404,
                'name' => 'Farming_func_area',
                'display_name' => 'Farming & Veterinary',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Engineering Functional Area.</p>',
                'attribute_value' => 'Agronomy & Farm Services, Farm Management, Horticulture, Vet & Animal Welfare, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:40:16',
                'updated_at' => '2017-04-28 17:40:16',
            ),
            24 => 
            array (
                'id' => 406,
                'name' => 'Govt & Defense_func_area',
                'display_name' => 'Government & Defense',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Farming &amp; Veterinary&nbsp;Functional Area.</p>',
                'attribute_value' => 'Army, Emergency Services, Navy, Police & Corrections, Policy Planning & Regulation, Government - Federal, Government - Local, Government - State, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:43:03',
                'updated_at' => '2017-04-28 17:43:03',
            ),
            25 => 
            array (
                'id' => 408,
                'name' => 'Healthcare_func_area',
                'display_name' => 'Healthcare & Nursing',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Government &amp; Defense&nbsp;Functional Area.</p>',
                'attribute_value' => 'Chiropractic & Osteopathic, Clinical/Medical Research, Dental, Dieticians, Environmental Services, General Practitioners, Management, Medical Administration, Medical Imaging, Medical Specialists, Natural Therapies & Alternative Medicine, Nursing - A&E Critical Care & ICU, Nursing - Aged Care, Nursing - Community Maternal & Child Health, Nursing - Educators & Facilitators, Nursing - General Medical & Surgical, Nursing - High Acuity, Nursing - Management, Nursing - Midwifery Neo-Natal SCN & NICU, Nursing - Pediatric & PICU, Nursing - Psych, Forensic & Correctional Health, Nursing - Theatre & Recovery, Optical, Pathology, Pharmaceuticals & Medical Devices, Pharmacy, Physiotherapy OT & Rehabilitation, Psychology, Counselling & Social Work, Residents & Registrars Sales, Speech Therapy, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:48:49',
                'updated_at' => '2017-04-28 17:48:49',
            ),
            26 => 
            array (
                'id' => 409,
                'name' => 'Hospitality_func_area',
                'display_name' => 'Hospitality & Tourism',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Healthcare &amp; Nursing&nbsp;Functional Area.</p>',
                'attribute_value' => 'Bar & Beverage Staff, Chefs/Cooks, Front Office & Guest Services, Gaming, Housekeeping, Kitchen & Sandwich, Hands Management, Reservations, Tour Guides, Travel Agents/Consultants, Waiting Staff, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:51:18',
                'updated_at' => '2017-04-28 17:51:18',
            ),
            27 => 
            array (
                'id' => 410,
                'name' => 'Technology _func_area',
                'display_name' => 'Information & Communication Technology ',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of&nbsp;Hospitality &amp; Tourism Functional Area.</p>',
                'attribute_value' => 'Business/Systems Analysts, Computer Operators, Consultants, Database Development & Administration, Developers/Programmers, Engineering - Hardware, Engineering - Network, Engineering - Software, Help Desk & IT, Support, Management, Networks & Systems Administration, Product Management & Development, Programme & Project Management, Sales - Pre & Post, Security, Team Leaders, Technical Writing, Telecommunications, Testing & Quality Assurance, Web Development & Production, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:54:49',
                'updated_at' => '2017-04-28 17:54:49',
            ),
            28 => 
            array (
                'id' => 411,
                'name' => 'Transport & Logistics_func_area',
                'display_name' => 'Manufacturing, Transport & Logistics',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of Information &amp; Communication Technology Functional Area.</p>',
                'attribute_value' => 'Assembly & Process Work, Aviation Services, Couriers, Drivers & Postal Services, Fleet Management, Freight/Cargo Forwarding, Import/Export & Customs, Machine Operators, Management, Pattern Makers & Garment Technicians, Pickers & Packers, Production, Planning & Scheduling, Public Transport & Taxi Services, Purchasing, Procurement & Inventory, Quality Assurance & Control, Rail & Maritime Transport, Road Transport, Team Leaders/Supervisors, Warehousing, Storage & Distribution, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 17:58:45',
                'updated_at' => '2017-04-28 17:58:45',
            ),
            29 => 
            array (
                'id' => 412,
                'name' => 'Marketing_func_area',
                'display_name' => 'Marketing & Communications',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of Manufacturing, Transport &amp; Logistics Functional Area.</p>',
                'attribute_value' => 'Digital & Search Marketing, Direct Marketing & CRM, Event Management, Internal Communications Management, Market Research & Analysis, Marketing Assistants/Coordinators, Marketing Communications, Product Management & Development, Public Relations & Corporate Affairs, Trade Marketing, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 18:00:58',
                'updated_at' => '2017-04-28 18:00:58',
            ),
            30 => 
            array (
                'id' => 413,
                'name' => 'Resources & Energy_func_area',
                'display_name' => 'Mining, Resources & Energy',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of Marketing &amp; Communications Functional Area.</p>',
                'attribute_value' => 'Health, Safety & Environment Management, Mining - Drill & Blast, Mining - Engineering & Maintenance, Mining - Exploration & Geoscience, Mining - Operations, Mining - Processing, Natural Resources & Water, Oil & Gas - Drilling, Oil & Gas - Engineering & Maintenance, Oil & Gas - Exploration & Geoscience, Oil & Gas - Operations, Oil & Gas - Production & Refinement, Power Generation & Distribution, Surveying, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 18:08:55',
                'updated_at' => '2017-04-28 18:08:55',
            ),
            31 => 
            array (
                'id' => 414,
                'name' => 'Property _func_area',
                'display_name' => 'Real Estate & Property ',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of Mining, Resources &amp; Energy Functional Area.</p>',
                'attribute_value' => 'Analysts, Body Corporate & Facilities Management, Commercial Sales Leasing & Property Mgmt, Residential Leasing & Property Management, Residential Sales, Retail & Property Development, Valuation, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 18:11:03',
                'updated_at' => '2017-04-28 18:11:03',
            ),
            32 => 
            array (
                'id' => 415,
                'name' => 'Consumer Products _func_area',
                'display_name' => 'Retail and Consumer Products',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of Real Estate &amp; Property Functional Area.</p>',
                'attribute_value' => 'Management - Area/Multi-site, Management - Department/Assistant, Management - Store, Merchandisers, Planning, Retail Assistants, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 18:12:31',
                'updated_at' => '2017-04-28 18:12:31',
            ),
            33 => 
            array (
                'id' => 416,
                'name' => 'Sales _func_area',
                'display_name' => 'Sales',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of Retail and Consumer Products Functional Area.</p>',
                'attribute_value' => 'Analysis & Reporting, Management, Business Development, Sales Coordinators, Sales Representatives/Consultants, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 18:13:45',
                'updated_at' => '2017-04-28 18:13:45',
            ),
            34 => 
            array (
                'id' => 417,
                'name' => 'Trades _func_area',
                'display_name' => 'Trades & Services ',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of Sports &amp; Recreation Functional Area.</p>',
                'attribute_value' => 'Analysis & Reporting, Automotive Trades, Bakers & Pastry Chefs, Building Trades, Butchers, Carpentry & Cabinet Making, Cleaning Services, Electricians, Fitters, Turners & Machinists, Floristry, Gardening & Landscaping, Hair & Beauty Services, Laborers, Locksmiths, Maintenance & Handyperson Services, Nannies & Babysitters, Painters & Sign Writers, Plumbers, Printing & Publishing Services, Security Services, Tailors & Dressmakers, Technicians, Welders & Boilermakers, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 18:18:41',
                'updated_at' => '2017-04-28 18:18:41',
            ),
            35 => 
            array (
                'id' => 418,
                'name' => 'Other Jobs _func_area',
                'display_name' => 'Other Jobs ',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List of &nbsp;Trades &amp; Services&nbsp;Functional Area.</p>',
                'attribute_value' => 'Other Jobs ',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 18:20:14',
                'updated_at' => '2017-04-28 18:20:14',
            ),
            36 => 
            array (
                'id' => 419,
                'name' => 'service_opening_hour',
                'display_name' => 'Operating Hours',
                'p_attr_id' => 0,
                'attributetype_id' => 1,
                'description' => '<p>Time when the business will open and close</p>',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '/tmp/phpL2QZyx',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 18:59:25',
                'updated_at' => '2017-04-29 03:15:11',
            ),
            37 => 
            array (
                'id' => 420,
                'name' => 'type_auto_service',
                'display_name' => 'Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the type of services for Automotive</p>',
                'attribute_value' => 'Mechanics,Garages,Cars, Trailers,  Excavators Hire,Paint, Body Repair,Other Automotive',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 19:07:45',
                'updated_at' => '2017-04-28 19:07:45',
            ),
            38 => 
            array (
                'id' => 421,
                'name' => 'building_services',
                'display_name' => 'Service Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>All type of the service included in the Building section</p>',
                'attribute_value' => 'Air Conditioning & Heating,Bricklaying,Carpentry,Concreting & Paving,Electrical,Fencing & Gates,Flooring,Handyman, Painting & Decorating,Pest Control,Plastering & Tiling,Plumbing,Roofing,Rubbish Removal & Skip Hiring, Scaffolding,Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 19:12:23',
                'updated_at' => '2017-04-28 19:12:23',
            ),
            39 => 
            array (
                'id' => 422,
                'name' => 'service_comp_telecomm',
                'display_name' => 'Service Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the services for Technician&nbsp;</p>',
                'attribute_value' => 'Computer & Phone Repairs,Graphic & Web Design,Web Development,Online Marketing,Other Computer, Telecom & Freelance,,Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 19:15:06',
                'updated_at' => '2017-04-28 23:51:24',
            ),
            40 => 
            array (
                'id' => 423,
                'name' => 'service_beauty',
                'display_name' => 'Service Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the services in the Health section</p>',
                'attribute_value' => 'Beauty Treatments,Hairdressing,Personal Training,Massages,Alternative Therapies, Others',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 19:42:16',
                'updated_at' => '2017-04-28 19:42:16',
            ),
            41 => 
            array (
                'id' => 424,
                'name' => 'service_hire',
                'display_name' => 'Service Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the services under for Hire section</p>',
                'attribute_value' => 'Party Hire, Baby Products Hire, Bands, Entertainers & Staff Hire, Car Hire, Trailers & Excavators Hire,Tools & Equipment Hire, Furniture & Appliances Hire,Other Hiring',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 19:44:34',
                'updated_at' => '2017-04-28 19:44:34',
            ),
            42 => 
            array (
                'id' => 425,
                'name' => 'service_learning_tutoring',
                'display_name' => 'Type of Service',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all kind of services under Learning &amp; Tutoring</p>',
                'attribute_value' => 'HSC, University & School Tutoring,Courses Training,Music Tutoring,Dance Training,Swimming lessons,Language Learning & Tutoring, Professional Tutoring, Other',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 19:53:23',
                'updated_at' => '2017-04-28 19:53:23',
            ),
            43 => 
            array (
                'id' => 426,
                'name' => 'pet_service',
                'display_name' => 'Service Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List All the Types of Services for Pet</p>',
                'attribute_value' => 'Sitting,Grooming,Training,Other Pet Services',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 20:46:06',
                'updated_at' => '2017-04-28 23:50:09',
            ),
            44 => 
            array (
                'id' => 427,
                'name' => 'electronic',
                'display_name' => 'Product',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>Type of Software and Electronic components</p>',
                'attribute_value' => 'Laptops,Desktops,Computer Accessories,Components,Printers & Scanners,Modems & Routers,Monitors,Hard Drives & USB Sticks,Software,Other Computers & Software',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '/tmp/phpIcqpkV',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 20:49:18',
                'updated_at' => '2017-04-28 20:49:18',
            ),
            45 => 
            array (
                'id' => 428,
                'name' => 'type_of_console',
                'display_name' => 'Product',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the Video game and console assecorries</p>',
                'attribute_value' => 'Playstation,Xbox,Wii,Video Games,Console Accessories,Other Consoles',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '/tmp/phpNaDRqI',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 20:51:43',
                'updated_at' => '2017-04-28 20:51:43',
            ),
            46 => 
            array (
                'id' => 429,
                'name' => 'type_of_phones',
                'display_name' => 'Product',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>List all the&nbsp;</p>',
                'attribute_value' => 'Android Phone, Home Phones, iPhone,Phone Accessories,Other Phones',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '/tmp/phpOhuIfI',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 21:02:06',
                'updated_at' => '2017-04-28 23:42:24',
            ),
            47 => 
            array (
                'id' => 430,
                'name' => 'hobbies',
                'display_name' => 'hobbies',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>test</p>',
                'attribute_value' => 'cricket,chess',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-28 21:34:12',
                'updated_at' => '2017-04-28 21:34:12',
            ),
            48 => 
            array (
                'id' => 432,
                'name' => 'car_model',
                'display_name' => 'Model',
                'p_attr_id' => 372,
                'attributetype_id' => 4,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-04-29 00:33:49',
                'updated_at' => '2017-04-29 00:36:03',
            ),
            49 => 
            array (
                'id' => 433,
                'name' => 'property_type',
                'display_name' => 'Property Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '',
                'attribute_value' => 'Lease,Buy,Sell,Businessforsale,OfficeSpace,Others.',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '20581.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-05-03 17:01:09',
                'updated_at' => '2017-11-13 13:44:09',
            ),
            50 => 
            array (
                'id' => 434,
                'name' => 'rural_lease_type',
                'display_name' => 'Lease Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '',
                'attribute_value' => 'LeaseBuySell',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-05-03 17:27:46',
                'updated_at' => '2017-05-03 17:27:46',
            ),
            51 => 
            array (
                'id' => 435,
                'name' => 'domestic_add_type',
                'display_name' => 'Domestic Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '',
                'attribute_value' => 'Lease,Buy,Sell,Flatshare&Houseshare',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-05-03 17:29:22',
                'updated_at' => '2017-05-03 17:29:22',
            ),
            52 => 
            array (
                'id' => 436,
                'name' => 'others_add_type',
                'display_name' => 'Others Type',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '',
                'attribute_value' => 'Shortterm,Parkingspace',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-05-03 17:30:25',
                'updated_at' => '2017-05-03 17:30:25',
            ),
            53 => 
            array (
                'id' => 437,
                'name' => 'food_packaging',
                'display_name' => 'Packaging',
                'p_attr_id' => 0,
                'attributetype_id' => 1,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-05-05 14:18:43',
                'updated_at' => '2017-05-05 14:18:43',
            ),
            54 => 
            array (
                'id' => 438,
                'name' => 'food_certification',
                'display_name' => 'Certification Type',
                'p_attr_id' => 0,
                'attributetype_id' => 5,
                'description' => '',
                'attribute_value' => 'Halal,Vegan,Kosher,NotCertified,Haram',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-05-05 14:20:28',
                'updated_at' => '2017-05-05 14:20:28',
            ),
            55 => 
            array (
                'id' => 439,
                'name' => 'Car Name',
                'display_name' => 'Car Name',
                'p_attr_id' => 0,
                'attributetype_id' => 1,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-09-12 15:17:03',
                'updated_at' => '2017-09-12 15:17:03',
            ),
            56 => 
            array (
                'id' => 440,
                'name' => 'demo1asda',
                'display_name' => 'asd as',
                'p_attr_id' => 0,
                'attributetype_id' => 9,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => 'asdad',
                'metadescription' => 'asdasd ',
                'created_at' => '2017-09-28 11:10:54',
                'updated_at' => '2017-11-15 10:27:02',
            ),
            57 => 
            array (
                'id' => 442,
                'name' => 'fordate',
                'display_name' => 'frdate',
                'p_attr_id' => 0,
                'attributetype_id' => 19,
                'description' => '',
                'attribute_value' => 'on',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => 'sd s',
                'metadescription' => ' s',
                'created_at' => '2017-09-30 09:29:12',
                'updated_at' => '2017-10-04 07:20:42',
            ),
            58 => 
            array (
                'id' => 443,
                'name' => 'newDDAtr',
                'display_name' => 'newDDAtr',
                'p_attr_id' => 0,
                'attributetype_id' => 4,
                'description' => '<p>as a a</p>
',
                'attribute_value' => 'new1,new2,new3',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => 'as ad a d',
                'metadescription' => ' dasd ',
                'created_at' => '2017-10-03 10:18:38',
                'updated_at' => '2017-10-03 10:18:38',
            ),
            59 => 
            array (
                'id' => 444,
                'name' => 'videoType',
                'display_name' => 'videoType',
                'p_attr_id' => 0,
                'attributetype_id' => 17,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 0,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => 'as d',
                'metadescription' => ' as',
                'created_at' => '2017-10-03 10:53:39',
                'updated_at' => '2017-10-13 11:43:21',
            ),
            60 => 
            array (
                'id' => 445,
                'name' => 'videoOneMore',
                'display_name' => 'videoOneMore',
                'p_attr_id' => 0,
                'attributetype_id' => 17,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 0,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-10-04 05:51:04',
                'updated_at' => '2017-10-13 11:43:10',
            ),
            61 => 
            array (
                'id' => 446,
                'name' => 'vvvddee',
                'display_name' => 'vvvddee',
                'p_attr_id' => 0,
                'attributetype_id' => 17,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 0,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-10-04 12:05:49',
                'updated_at' => '2017-10-13 11:42:56',
            ),
            62 => 
            array (
                'id' => 447,
                'name' => 'calendarRang',
                'display_name' => 'calendarRang',
                'p_attr_id' => 0,
                'attributetype_id' => 8,
                'description' => '',
                'attribute_value' => '1960,2015',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-08 06:41:46',
                'updated_at' => '2017-11-08 06:41:46',
            ),
            63 => 
            array (
                'id' => 448,
                'name' => 'multiSelect',
                'display_name' => 'multiSelect',
                'p_attr_id' => 0,
                'attributetype_id' => 5,
                'description' => '',
                'attribute_value' => 'one,two,three,four',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-08 07:21:58',
                'updated_at' => '2017-11-08 07:21:58',
            ),
            64 => 
            array (
                'id' => 449,
                'name' => 'EmailAttr',
                'display_name' => 'EmailAttr',
                'p_attr_id' => 0,
                'attributetype_id' => 3,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-08 07:42:36',
                'updated_at' => '2017-11-08 07:43:24',
            ),
            65 => 
            array (
                'id' => 450,
                'name' => 'numericRange',
                'display_name' => 'numericRange',
                'p_attr_id' => 0,
                'attributetype_id' => 18,
                'description' => '',
                'attribute_value' => '400,2400',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-08 09:11:29',
                'updated_at' => '2017-11-08 09:11:29',
            ),
            66 => 
            array (
                'id' => 451,
                'name' => 'TimeRange',
                'display_name' => 'TimeRange',
                'p_attr_id' => 0,
                'attributetype_id' => 13,
                'description' => '',
                'attribute_value' => 'on',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '31118.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-08 09:35:24',
                'updated_at' => '2017-11-10 10:11:26',
            ),
            67 => 
            array (
                'id' => 452,
                'name' => 'time',
                'display_name' => 'time',
                'p_attr_id' => 0,
                'attributetype_id' => 13,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-08 09:58:31',
                'updated_at' => '2017-11-08 09:58:31',
            ),
            68 => 
            array (
                'id' => 453,
                'name' => 'textArea',
                'display_name' => 'textArea',
                'p_attr_id' => 0,
                'attributetype_id' => 2,
                'description' => '<p>as dasd</p>
',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-08 11:00:05',
                'updated_at' => '2017-11-08 11:00:05',
            ),
            69 => 
            array (
                'id' => 454,
                'name' => 'oneMoreMultiSelect',
                'display_name' => 'oneMoreMultiSelect',
                'p_attr_id' => 0,
                'attributetype_id' => 5,
                'description' => '',
                'attribute_value' => '1111,2222,3333,4444',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-09 09:36:05',
                'updated_at' => '2017-11-09 09:36:05',
            ),
            70 => 
            array (
                'id' => 455,
                'name' => 'Available Color',
                'display_name' => 'Available Color',
                'p_attr_id' => 0,
                'attributetype_id' => 5,
                'description' => '',
                'attribute_value' => 'Red,Blue,Green,Black',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 1,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-14 12:30:34',
                'updated_at' => '2017-11-14 12:32:27',
            ),
            71 => 
            array (
                'id' => 456,
                'name' => 'About the job role',
                'display_name' => 'About the job role',
                'p_attr_id' => 0,
                'attributetype_id' => 2,
                'description' => '<p>About the job roleAbout the job roleAbout the job roleAbout the job roleAbout the job roleAbout the job roleAbout the job roleAbout the job roleAbout the job role</p>
',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '37565.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-16 11:06:45',
                'updated_at' => '2017-11-16 11:06:45',
            ),
            72 => 
            array (
                'id' => 457,
                'name' => 'About the company',
                'display_name' => 'About the company',
                'p_attr_id' => 0,
                'attributetype_id' => 2,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 0,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '15291.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-16 11:07:17',
                'updated_at' => '2017-11-18 06:14:25',
            ),
            73 => 
            array (
                'id' => 458,
                'name' => 'company_name',
                'display_name' => 'Company Name',
                'p_attr_id' => 0,
                'attributetype_id' => 1,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '59920.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-17 06:00:42',
                'updated_at' => '2017-11-17 06:00:42',
            ),
            74 => 
            array (
                'id' => 459,
                'name' => 'Tobecomesuccessfulcandidate',
                'display_name' => 'To become a successful candidate',
                'p_attr_id' => 0,
                'attributetype_id' => 2,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-18 07:06:07',
                'updated_at' => '2017-11-18 07:06:07',
            ),
            75 => 
            array (
                'id' => 460,
                'name' => 'The benefit you will get',
                'display_name' => 'The benefit you will get',
                'p_attr_id' => 0,
                'attributetype_id' => 2,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-18 07:07:02',
                'updated_at' => '2017-11-18 07:07:02',
            ),
            76 => 
            array (
                'id' => 461,
                'name' => 'HowtoApply',
                'display_name' => 'How to Apply',
                'p_attr_id' => 0,
                'attributetype_id' => 2,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 0,
                'icon' => '',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2017-11-18 07:07:51',
                'updated_at' => '2017-11-18 07:07:51',
            ),
            77 => 
            array (
                'id' => 462,
                'name' => 'qwerty Att 1',
                'display_name' => 'qwerty Att 1',
                'p_attr_id' => 0,
                'attributetype_id' => 17,
                'description' => '',
                'attribute_value' => '',
                'size' => 0,
                'measure_unit' => '',
                'required' => 1,
                'searchable' => 0,
                'status' => 1,
                'show_type' => NULL,
                'show_list' => 1,
                'icon' => '43653.png',
                'metatitle' => '',
                'metadescription' => '',
                'created_at' => '2018-01-10 06:28:48',
                'updated_at' => '2018-01-10 06:28:48',
            ),
        ));
        
        
    }
}